namespace: prod

appName: rest-api

port: 3000

image:
  name: zdgul/myapp
  tag: rest-api-4.3

configmap:
  name: rest-api-configmap
  data:
    ENV: 'PROD'
    DBURL: 'mongodb+srv://my-rest-api:my-rest-api@my-rest-api.9nx2ruj.mongodb.net/'