appName: rest-api

port: 3000

namespace: default

configmap:
  name: rest-api-configmap
  data: 
    ENV: 'DEV'
    DBURL: 'mongodb+srv://my-rest-api:my-rest-api@my-rest-api.9nx2ruj.mongodb.net/'


image:
  name: zdgul/myapp
  tag: rest-api-4.3