appName: rest-api

port: 3000

namespace: default

configmap:
  name: rest-api-configmap
  data: 
    ENV: 'DEV'
    PORT: '3000'
    DBEND: '@my-rest-api.9nx2ruj.mongodb.net/'
    DBSTART: +srv://my-rest-api:'


image:
  name: zdgul/myapp
  tag: rest-api-4.1